### ISSUE TITLE
Failed to activate the atom-python-package package

### ISSUE THREAD

**Issue by DroidRazr** [aeikenberry/atom-python-package#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-python-package](https://github.com/aeikenberry/atom-python-package) package 0.7.1

### Stack Trace

Failed to activate the atom-python-package package

```
At Cannot read property 'endsWith' of undefined

TypeError: Cannot read property 'endsWith' of undefined
    at Object.setDir (/packages/atom-python-package/lib/atom-python-package.js:94:14)
    at Object.resetDefaultText (/packages/atom-python-package/lib/atom-python-package.js:99:10)
    at Object.activate (/packages/atom-python-package/lib/atom-python-package.js:19:10)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:1022:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.2/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.2/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -6:35.4.0 core:backspace (input.hidden-input)
     -6:32.3.0 core:confirm (input.hidden-input)
     -0:38.3.0 atom-python-package:toggle (div.panels-item)
```

### Non-Core Packages

```
atom-python-package 0.7.1 
atom-python-run 0.9.5 
atom-python-test 0.9.0 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.10.5 
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
ide-python 0.4.0 
intentions 1.1.5 
kite 0.58.0 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.6.10 
python-debugger 0.2.0 
python-indent 1.1.4 
python-snippets 1.9.0 
python-suite 0.3.2 
python-tools 0.6.9 
run-python-simply 0.4.0 
```

**Comment by DroidRazr** [comment]
Going to try it another way.

**Comment by aeikenberry** [comment]
Ok good luck sir, thanks for reporting

**Comment by DroidRazr** [comment]
Going to need the luck because I don't know what hell I am doing.  Trying to learn this stuff on my free time.
