### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'D:/Program Files\Microsoft VS Code\resource...

### ISSUE THREAD

**Issue by 9994444ggg** [aeikenberry/atom-python-package#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: DESKTOP-T6NUSO
**Thrown From**: [atom-python-package](https://github.com/aeikenberry/atom-python-package) package 0.7.1

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'D:\Program Files\Microsoft VS Code\resources\app\extensions\.vscode//__init__.py'

```
At fs.js:143

Error: EPERM: operation not permitted, open 'D:\Program Files\Microsoft VS Code\resources\app\extensions\.vscode//__init__.py'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at openThenF (/packages/atom-python-package/node_modules/touch/touch.js:76:40)
    at touch_ (/packages/atom-python-package/node_modules/touch/touch.js:69:10)
    at optionsRef (/packages/atom-python-package/node_modules/touch/touch.js:41:28)
    at touch (/packages/atom-python-package/node_modules/touch/touch.js:65:10)
    at /packages/atom-python-package/lib/atom-python-package.js:49:9
    at /packages/atom-python-package/node_modules/mkdirp/index.js:38:26
    at FSReqWrap.oncomplete (fs.js:183:5)
```

### Commands

```
     -1:31.9.0 git-projects-manager:Refresh projects (div.package-detail)
     -1:22 github:toggle-git-tab (div.package-detail)
     -0:36.3.0 git-plus-context:diff-all (span.name.icon.icon-file-directory)
     -0:20.5.0 git-plus-context:diff-branches (span.name.icon.icon-file-directory)
     -0:08.3.0 atom-python-package:toggleAtDir (span.name.icon.icon-file-directory)
     -0:05.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-package 0.7.1 
atom-python-run 0.9.7 
git-auto-stash 0.2.4 
git-control 0.9.0 
git-gerrit 0.4.0 
git-plus 8.7.1 
git-projects-manager 1.0.0 
ide-python 1.4.2 
ipython-exec 1.2.0 
python-import-magic 2.0.0 
python-isort 0.0.7 
run-python-simply 0.6.0 
teletype 0.13.4 
```

**Comment by aeikenberry** [comment]
Thanks for reporting. Give me a bit to look into it.

**Comment by 9994444ggg** [comment]
Please let me a Little bit time i am workself in Moment with my installations files.Thanks for your question

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Aaron Eikenberry <notifications@github.com>
Gesendet: Wednesday, October 23, 2019 9:51:43 PM
An: aeikenberry/atom-python-package <atom-python-package@noreply.github.com>
Cc: Günther Harth <g.harth@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [aeikenberry/atom-python-package] Uncaught Error: EPERM: operation not permitted, open 'D:/Program Files\Microsoft VS Code\resource... (#5)


Thanks for reporting. Give me a bit to look into it.
